server: 
  context-path: /ssd
  port: 8090

spring: 
  datasource: 
    url: jdbc:mysql://192.168.43.132:3306/main_smmsdemo
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  http: 
    encoding: 
      charset: UTF-8
    jackson: 
      date-format: yyyy-MM-dd HH:mm:ss 
      timeZone: Asia/Shanghai
    resources: 
      chain: 
        enabled: true

secondary: 
  datasource: 
      url: jdbc:mysql://192.168.43.132:3306/target_smmsdemo
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      
#mybatis: 
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.sizatn.ssd.entity

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
logging: 
  config: classpath:logback-boot.xml
  
