server: 
  servlet: 
    context-path:  /ssd
  port: 8090

spring: 
  datasource:
    druid: 
      primary: 
        url: jdbc:mysql://192.168.0.101:3306/main_smmsdemo
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        max-active: 10
        initial-size: 1
        max-wait: 60000
        min-idle: 5
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
      secondary: 
        url: jdbc:mysql://192.168.0.101:3306/target_smmsdemo
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        max-active: 10
        initial-size: 1
        max-wait: 60000
        min-idle: 5
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
  http: 
    encoding: 
      charset: utf-8
    jackson: 
      date-format: yyyy-mm-dd hh:mm:ss 
      timezone: asia/shanghai
    resources: 
      chain: 
        enabled: true
  cache: 
    type: REDIS
  redis: 
    database: 0
    hostName: 192.168.43.216
    port: 6379
    # Login password of the redis server.
    password: foobared
    timeout: 0
    lettuce: 
      pool: 
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
        shutdown-timeout: 100
    sentinel: 
      # Name of Redis server.
      master:
      # Comma-separated list of host:port pairs. 
      nodes:
  dubbo: 
    scan: com.sizatn.ssd.dubbo
    application: 
      name: provider
    registry: 
      protocol: zookeeper
      address: 200.20.2.160
      port: 2181
    protocol: 
      name: dubbo
      port: 20880
      
#mybatis: 
#  mapperLocations: classpath*:mapper/*.xml
#  typeAliasesPackage: com.sizatn.ssd.entity

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
logging: 
  config: classpath:logback-boot.xml
